name: Ultimate Master Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Python Setup
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install Dependencies
      run: pip install customtkinter pymem pyinstaller
    - name: Final Build
      run: pyinstaller --noconfirm --onefile --windowed --noconsole --name "WinUpdateService_v10" main.py
    - name: Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Master_Engine_EXE
        path: dist/WinUpdateService_v10.exe
        
