name: Ultimate Ghost Engine Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install customtkinter pymem pyinstaller

    - name: Build Private EXE
      run: |
        # --noconsole: Siyah ekranı kapatır, --windowed: UI modunda çalıştırır
        pyinstaller --noconfirm --onefile --windowed --noconsole --name "WinUpdateService" main.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Yahya_Private_Engine
        path: dist/WinUpdateService.exe
        
